apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: osaan-istio
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: jaeger-all-in-one.istio-system:9411
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
