name: competence-matching-service
svcName: competence-matching-svc

image:
  repository: miguelsombrero/osaan-competence-matching-service
  tag: latest

rabbitmq:
  enabled: true

configMap:
  data:
    SPRING_MAIL_HOST: mailhog-svc
    SPRING_MAIL_PORT: "1025"
    TRACING_ENDPOINT: http://jaeger-collector.istio-system:9411/api/v2/spans
    LOGGING_LEVEL_WEB: DEBUG
    LOGGING_LEVEL_APPLICATION: DEBUG
    ISSUER_URI: https://keycloak.local/realms/osaan
    JAVA_TOOL_OPTIONS: >-
      -Djavax.net.ssl.trustStore=/opt/java/keycloak-truststore.jks
      -Djavax.net.ssl.trustStorePassword=changeit
