name: skill-catalog-service
svcName: skill-catalog-svc

image:
  repository: miguelsombrero/osaan-skill-catalog-service
  tag: latest

redis:
  enabled: true

configMap:
  data:
    TRACING_ENDPOINT: http://jaeger.istio-system:9411/api/v2/spans
    LOGGING_LEVEL_APPLICATION: TRACE
    ISSUER_URI: https://keycloak.local/realms/osaan
    SPRING_DATA_REDIS_HOST: valkey.osaan-dev.svc.cluster.local
    JAVA_TOOL_OPTIONS: >-
      -Djavax.net.ssl.trustStore=/opt/java/keycloak-truststore.jks
      -Djavax.net.ssl.trustStorePassword=changeit
