services:
  # -----------------
  # Common services
  # -----------------
  mailhog:
    image: mailhog/mailhog
    container_name: osaan-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - ./maildir:/maildir

  rabbitmq:
    image: rabbitmq:4-management
    container_name: osaan-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  # One DB for all microservices for simplicity in development
  osaan-db:
    image: postgres:latest
    container_name: osaan-db
    restart: always
    environment:
      POSTGRES_PASSWORD: osaan_pass
    ports:
      - "5432:5432"
    volumes:
      - osaan-data:/var/lib/postgresql/data

  zipkin-server:
    image: openzipkin/zipkin:2.24.0
    restart: always
    mem_limit: 1024m
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  # -----------------
  # Microservices
  # -----------------
  employee-service:
    build: ./microservices/employee-service
    container_name: employee-service
    depends_on:
      - osaan-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8091:8080"

  skill-catalog-service:
    build: ./microservices/skill-catalog-service
    container_name: skill-catalog-service
    depends_on:
      - osaan-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8092:8080"

  competence-profile-service:
    build: ./microservices/competence-profile-service
    container_name: competence-profile-service
    depends_on:
      - osaan-db
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8093:8080"

  competence-matching-service:
    build: ./microservices/competence-matching-service
    container_name: competence-matching-service
    depends_on:
      - osaan-db
      - mailhog
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8094:8080"

volumes:
  osaan-data:
