services:
  mailhog:
    image: mailhog/mailhog
    container_name: osaan-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - ./maildir:/maildir

  rabbitmq:
    image: rabbitmq:4-management
    container_name: osaan-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  # One DB for all microservices for simplicity in development
  osaan-db:
    image: postgres:latest
    container_name: osaan-db
    restart: always
    environment:
      POSTGRES_PASSWORD: osaan_pass
    ports:
      - "5432:5432"
    volumes:
      - osaan-data:/var/lib/postgresql/data

  zipkin-server:
    image: openzipkin/zipkin:2.24.0
    restart: always
    mem_limit: 1024m
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_ALERTING_ENABLED=true
      #- GF_UNIFIED_ALERTING_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_HOST=mailhog:1025
      - GF_SMTP_FROM_ADDRESS=grafana@osaan.com
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  # -----------------
  # Microservices
  # -----------------
  employee-service:
    build: ./microservices/employee-service
    container_name: employee-service
    depends_on:
      - osaan-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8091:8080"
      - "4001:4004"

  skill-catalog-service:
    build: ./microservices/skill-catalog-service
    container_name: skill-catalog-service
    depends_on:
      - osaan-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8092:8080"
      - "4002:4004"

  competence-profile-service:
    build: ./microservices/competence-profile-service
    container_name: competence-profile-service
    depends_on:
      - osaan-db
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8093:8080"
      - "4003:4004"

  competence-matching-service:
    build: ./microservices/competence-matching-service
    container_name: competence-matching-service
    depends_on:
      - osaan-db
      - mailhog
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8094:8080"
      - "4004:4004"

  osaan-admin-backend:
    build: ./ui/osaan-admin-ui/backend
    container_name: osaan-admin-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TARGET_API=http://skill-catalog-service:8080
      - SESSION_SECRET=mysecret
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:8080
      - REDIS_ENABLED=true
      - REDIS_URL=redis://osaan-redis:6379
      - KEYCLOAK_ENABLED=false
    depends_on:
      - osaan-redis

  osaan-admin-ui:
    build: ./ui/osaan-admin-ui/frontend
    container_name: osaan-admin-ui
    ports:
      - "8080:80"
    environment:
      - API_URL=http://osaan-admin-backend:3001/api
    depends_on:
      - osaan-admin-backend

  osaan-redis:
    image: redis:8-alpine
    container_name: osaan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  osaan-data:
  redis-data:
