apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/common/mailhog.yaml
  - manifests/common/rabbitmq.yaml
  - manifests/employee-service/configmap.yaml
  - manifests/employee-service/deployment.yaml
  - manifests/employee-service/service.yaml
  - manifests/skill-catalog-service/configmap.yaml
  - manifests/skill-catalog-service/deployment.yaml
  - manifests/skill-catalog-service/service.yaml
  - manifests/competence-profile-service/configmap.yaml
  - manifests/competence-profile-service/deployment.yaml
  - manifests/competence-profile-service/service.yaml
  - manifests/competence-matching-service/configmap.yaml
  - manifests/competence-matching-service/deployment.yaml
  - manifests/competence-matching-service/service.yaml
  - manifests/gateway/grafana-gateway.yaml
  - manifests/gateway/jaeger-gateway.yaml
  - manifests/gateway/keycloak-gateway.yaml
  - manifests/gateway/keycloak-mesh-egress.yaml
  - manifests/gateway/kiali-gateway.yaml
  - manifests/gateway/mail-gateway.yaml
  - manifests/gateway/osaan-gateway.yaml
  - manifests/gateway/osaan-admin-gateway.yaml
  - manifests/gateway/argocd-gateway.yaml
  - manifests/osaan-admin-backend/configmap.yaml
  - manifests/osaan-admin-backend/deployment.yaml
  - manifests/osaan-admin-backend/service.yaml
  - manifests/osaan-admin-ui/configmap.yaml
  - manifests/osaan-admin-ui/deployment.yaml
  - manifests/osaan-admin-ui/service.yaml
images:
  - name: miguelsombrero/osaan-employee-service
    newTag: b25cbe4ab1ec0db640c4704f13e28f70e9039621
  - name: miguelsombrero/osaan-skill-catalog-service
    newTag: b25cbe4ab1ec0db640c4704f13e28f70e9039621
  - name: miguelsombrero/osaan-competence-profile-service
    newTag: b25cbe4ab1ec0db640c4704f13e28f70e9039621
  - name: miguelsombrero/osaan-competence-matching-service
    newTag: b25cbe4ab1ec0db640c4704f13e28f70e9039621
  - name: miguelsombrero/osaan-admin-ui-backend
    newTag: b25cbe4ab1ec0db640c4704f13e28f70e9039621
  - name: miguelsombrero/osaan-admin-ui-frontend
    newTag: 180d3efbae26397366c1eb29bc53801fd9af6fb3
