apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/common/microservices-destinationrules.yaml
  - manifests/employee-service/configmap.yaml
  - manifests/employee-service/deployment.yaml
  - manifests/employee-service/service.yaml
  - manifests/skill-catalog-service/configmap.yaml
  - manifests/skill-catalog-service/deployment.yaml
  - manifests/skill-catalog-service/service.yaml
  - manifests/competence-profile-service/configmap.yaml
  - manifests/competence-profile-service/deployment.yaml
  - manifests/competence-profile-service/service.yaml
  - manifests/competence-matching-service/configmap.yaml
  - manifests/competence-matching-service/deployment.yaml
  - manifests/competence-matching-service/service.yaml
  - manifests/gateway/grafana-gateway.yaml
  - manifests/gateway/jaeger-gateway.yaml
  - manifests/gateway/keycloak-gateway.yaml
  - manifests/gateway/keycloak-mesh-egress.yaml
  - manifests/gateway/kiali-gateway.yaml
  - manifests/gateway/mail-gateway.yaml
  - manifests/gateway/osaan-gateway.yaml
  - manifests/gateway/osaan-admin-gateway.yaml
  - manifests/gateway/argocd-gateway.yaml
  - manifests/osaan-admin-backend/configmap.yaml
  - manifests/osaan-admin-backend/deployment.yaml
  - manifests/osaan-admin-backend/service.yaml
  - manifests/osaan-admin-ui/configmap.yaml
  - manifests/osaan-admin-ui/deployment.yaml
  - manifests/osaan-admin-ui/service.yaml
  - manifests/osaan-ui/configmap.yaml
  - manifests/osaan-ui/deployment.yaml
  - manifests/osaan-ui/service.yaml
images:
  - name: miguelsombrero/osaan-employee-service
    newTag: 5405e6417972b9b2f33fc17032606931a3a5c17f
  - name: miguelsombrero/osaan-skill-catalog-service
    newTag: bf447c880d7007a5e85970427644d3047684f7f2
  - name: miguelsombrero/osaan-competence-profile-service
    newTag: 5405e6417972b9b2f33fc17032606931a3a5c17f
  - name: miguelsombrero/osaan-competence-matching-service
    newTag: bf447c880d7007a5e85970427644d3047684f7f2
  - name: miguelsombrero/osaan-admin-ui-backend
    newTag: 9f14ef1a6f3982417ecc50c7b2cc64fe6f7716f0
  - name: miguelsombrero/osaan-admin-ui-frontend
    newTag: 9f14ef1a6f3982417ecc50c7b2cc64fe6f7716f0
  - name: miguelsombrero/osaan-ui
    newTag: 5405e6417972b9b2f33fc17032606931a3a5c17f
