apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/platform/certificate/selfsigned-issuer.yaml
  - manifests/platform/certificate/osaan-certificate.yaml
  - manifests/platform/keycloak/keycloak-cert.yaml
  - manifests/platform/keycloak/keycloak-postgres-secret.yaml
  - manifests/platform/keycloak/keycloak-postgres.yaml
  - manifests/platform/keycloak/keycloak.yaml
  - manifests/platform/keycloak/keycloak-realm-import.yaml
  - manifests/platform/istio.yaml
  - manifests/common/mailhog.yaml
  - manifests/common/rabbitmq.yaml
  - manifests/employee-service/configmap.yaml
  - manifests/employee-service/deployment.yaml
  - manifests/employee-service/service.yaml
  - manifests/skill-catalog-service/configmap.yaml
  - manifests/skill-catalog-service/deployment.yaml
  - manifests/skill-catalog-service/service.yaml
  - manifests/competence-profile-service/configmap.yaml
  - manifests/competence-profile-service/deployment.yaml
  - manifests/competence-profile-service/service.yaml
  - manifests/competence-matching-service/configmap.yaml
  - manifests/competence-matching-service/deployment.yaml
  - manifests/competence-matching-service/service.yaml
  - manifests/gateway/grafana-gateway.yaml
  - manifests/gateway/jaeger-gateway.yaml
  - manifests/gateway/keycloak-gateway.yaml
  - manifests/gateway/keycloak-mesh-egress.yaml
  - manifests/gateway/kiali-gateway.yaml
  - manifests/gateway/mail-gateway.yaml
  - manifests/gateway/osaan-gateway.yaml
  - manifests/gateway/osaan-admin-gateway.yaml
  - manifests/osaan-admin-backend/configmap.yaml
  - manifests/osaan-admin-backend/deployment.yaml
  - manifests/osaan-admin-backend/service.yaml
  - manifests/osaan-admin-ui/configmap.yaml
  - manifests/osaan-admin-ui/deployment.yaml
  - manifests/osaan-admin-ui/service.yaml
