employee:
  service:
    url: http://localhost:8091

skill:
  service:
    url: http://localhost:8092

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.resilience: TRACE
    web: TRACE

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.health.circuitbreakers.enabled: true

server:
  port: 8093