spring:
  application:
    name: competence-profile-service
  cloud:
    stream:
      bindings:
        skillCreated-out-0:
          destination: skill.created.queue
    refresh:
      enabled: false # Compatibility issues with Spring Boot 4.0.0-SNAPSHOT
  sql:
    init:
      mode: always

management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
  #zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans
  #tracing.sampling.probability: 1.0