management.health.circuitbreakers.enabled: true

spring:
  application:
    name: competence-profile-service
  cloud:
    refresh:
      enabled: false # Compatibility issues with Spring Boot 4.0.0-SNAPSHOT
  sql:
    init:
      mode: always