employee:
  service:
    url: http://localhost:8091

skill:
  service:
    url: http://localhost:8092

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    web: DEBUG

server:
  port: 8093