APP_AUTH_DISABLED: true

employee:
  service:
    url: http://localhost:8091

skill:
  service:
    url: http://localhost:8092

logging:
  level:
    io.github.resilience4j: TRACE
    org.springframework.jdbc: DEBUG
    web: TRACE

management:
  server.port: 4001
  tracing.export.zipkin.endpoint: http://localhost:9411/api/v2/spans
  tracing.sampling.probability: 1.0

server:
  port: 8093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest # Default RabbitMQ credentials for local development

  LOGGING_LEVEL_APPLICATION: TRACE
