spring:
  application:
    name: competence-profile-service
  cloud:
    stream:
      bindings:
        skillCreated-out-0:
          destination: skill.created.queue
    refresh:
      enabled: false # Compatibility issues with Spring Boot 4.0.0-SNAPSHOT
  sql:
    init:
      mode: always