helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-employee-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:828a8134c0a52ba3c9686a7c25619e12ea78792b74598079b7323adb9bb458c7
    forcestring: true
