helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-competence-matching-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:4664540afe510558d55cd3931207ca6c744b7136012fc71806195adf5c903646
    forcestring: true
