helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-employee-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:97fb03f91c4cea78ccd357f5762aac7eab930445c6e5b80370f82f229af7058d
    forcestring: true
