helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-skill-catalog-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:bdf04c94ff55baa2aecc9fa9c9f11836387aca5648e089c2eaf7d1064a3f31af
    forcestring: true
