helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-competence-profile-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:a75d15feaf0f1ac3dbd182b21f596ec55f5da6791b3ab6765cc8fa79aee6aac5
    forcestring: true
