helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-competence-profile-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:a51938b464aa8cccc6582135c5fc54a1ab74deafc67e32535cc2cb05162f7d04
    forcestring: true
