helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-competence-profile-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:3db205f9feecb74a4b57ed267c36564230260126160759de080e77b146907223
    forcestring: true
