helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-competence-matching-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:d924ce49dea841056c2583d983632b03bd65cb38ee92a7528c260dee69f8917d
    forcestring: true
