helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-skill-catalog-service
    forcestring: true
  - name: image.tag
    value: latest@sha256:54f19b92c1a6941ae9fe19436cc7f3f7a4ea471be0a0969f168a55b3327940cd
    forcestring: true
