apiVersion: v1
kind: ConfigMap
metadata:
  name: competence-matching-service-config
  namespace: osaan-dev
data:
  POSTGRESQL_HOST: competence-matching-postgres
  SPRING_MAIL_HOST: mailhog-svc
  SPRING_MAIL_PORT: "1025"