apiVersion: v1
kind: ConfigMap
metadata:
  name: competence-matching-service-config
  namespace: osaan-dev
data:
  POSTGRESQL_HOST: competence-matching-postgres
  SPRING_MAIL_HOST: mailhog-svc
  SPRING_MAIL_PORT: "1025"
  TRACING_ENDPOINT: http://jaeger-collector.istio-system:9411/api/v2/spans
  LOGGING_LEVEL_WEB: DEBUG
  LOGGING_LEVEL_APPLICATION: DEBUG