apiVersion: apps/v1
kind: Deployment
metadata:
  name: competence-matching-service-dep
  namespace: osaan-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4004"
    prometheus.io/scheme: http
    prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: competence-matching-service
  template:
    metadata:
      labels:
        app: competence-matching-service
    spec:
      containers:
        - name: competence-matching-service
          image: miguelsombrero/competence-matching-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/readiness
              port: 4004
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/liveness
              port: 4004
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: competence-matching-service-config
            - secretRef:
                name: postgres-secret
          env:
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: port
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
