services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  zipkin:
    image: 'openzipkin/zipkin:2.24.0'
    restart: always
    mem_limit: 1024m
    environment:
      - 'STORAGE_TYPE=mem'
    ports:
      - '9411:9411'
