apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: osaan-postgres-store
    kind: SecretStore
  target:
    name: osaan-db-pguser-keycloakuser
  dataFrom:
  - extract:
      key: osaan-db-pguser-keycloakuser