logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        SQL: DEBUG
      springframework:
        jdbc: DEBUG
    web: DEBUG

server:
  port: ${PORT:8080}

spring:
  application:
    name: employee-service
  cloud:
    refresh:
      enabled: false # Compatibility issues with Spring Boot 4.0.0-SNAPSHOT
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/postgres"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: always