management:
  tracing.export.zipkin.endpoint: http://zipkin-server:9411/api/v2/spans
  tracing.sampling.probability: 1.0

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  datasource:
    url: jdbc:postgresql://osaan-db:5432/postgres
    username: postgres
    password: osaan_pass

ISSUER_URI: https://keycloak:8443/realms/osaan