apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: operators
spec:
  initialAdminPasswordSecret:
    name: argocd-secret
    key: argocd-admin-password

  server:
    insecure: true
    replicas: 1

  controller:
    replicas: 1

  repo:
    replicas: 1
