apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-catalog-service-config
  namespace: osaan-dev
data:
  TRACING_ENDPOINT: http://jaeger-collector.istio-system:9411/api/v2/spans
  LOGGING_LEVEL_APPLICATION: TRACE