apiVersion: v1
kind: ConfigMap
metadata:
  name: skill-catalog-service-config
  namespace: osaan-dev
data:
  POSTGRESQL_HOST: skill-catalog-postgres
  management.zipkin.tracing.endpoint: http://jaeger-collector.istio-system:9411/api/v2/spans