apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-catalog-service-dep
  namespace: osaan-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4004"
    prometheus.io/scheme: http
    prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-catalog-service
  template:
    metadata:
      labels:
        app: skill-catalog-service
    spec:
      containers:
        - name: skill-catalog-service
          image: miguelsombrero/osaan-skill-catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 4004
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 4004
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: skill-catalog-service-config
          env:
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: osaan-db-pguser-osaan-user
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: osaan-db-pguser-osaan-user
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osaan-db-pguser-osaan-user
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: osaan-db-pguser-osaan-user
                  key: user
          volumeMounts:
            - name: keycloak-truststore
              mountPath: /opt/java/keycloak-truststore.jks
              subPath: keycloak-truststore.jks
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: keycloak-truststore
          secret:
            secretName: keycloak-truststore
