apiVersion: v1
kind: ConfigMap
metadata:
  name: osaan-ui-config
  namespace: osaan-dev
data:
  SKILL_CATALOG_API_URL: http://skill-catalog-svc:80
  COMPETENCE_PROFILE_API_URL: http://competence-profile-svc:80
  EMPLOYEE_API_URL: http://employee-svc:80
