apiVersion: v1
kind: Secret # INSECURE: for development only
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: super-salainen
  POSTGRES_DB: keycloak
