apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: osaan-keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: osaan-db-primary.osaan-dev.svc
    port: 5432
    usernameSecret:
      name: osaan-db-pguser-keycloakuser
      key: user
    passwordSecret:
      name: osaan-db-pguser-keycloakuser
      key: password
    database: keycloakdb
  hostname:
    hostname: https://keycloak.local
    admin: https://keycloak.local
    strict: false
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    tlsSecret: keycloak-tls
  proxy:
    headers: xforwarded
