apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osaan-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSombrero/osaan.git
    targetRevision: dev
    path: manifests/platform/argocd
  directory:
    recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true