apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate/osaan-certificate.yaml
  - certificate/selfsigned-issuer.yaml
  - postgres/postgres.yaml
  - keycloak/keycloak.yaml
  - keycloak/keycloak-postgres-secret.yaml
  - keycloak/keycloak-cert.yaml
  - keycloak/keycloak-postgres.yaml
  - keycloak/keycloak-realm-import.yaml
  - argocd/argocd-osaan.yaml
  - istio/istio.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: osaan-db-pguser-osaan-user
        namespace: osaan-dev
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "keycloak"
          reflector.v1.k8s.emberstack.com/reflected-version: "1"
    target:
      kind: Secret
      name: osaan-db-pguser-osaan-user
      namespace: osaan-dev