apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate/osaan-certificate.yaml
  - certificate/selfsigned-issuer.yaml
  - postgres/postgres.yaml
  - keycloak/keycloak.yaml
  - keycloak/keycloak-postgres-secret.yaml
  - keycloak/keycloak-cert.yaml
  - keycloak/keycloak-postgres.yaml
  - keycloak/keycloak-realm-import.yaml
  - argocd/argocd-osaan.yaml
  - istio/istio.yaml