helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-admin-ui-backend
    forcestring: true
  - name: image.tag
    value: latest@sha256:f6309abd1b33bd259074985445139463493d49b1c663bfbaa3c49412c5ede0c9
    forcestring: true
