helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-ui
    forcestring: true
  - name: image.tag
    value: latest@sha256:c85b0cd904490b71c6dc6a2f88adf764466352ebdefc78dd35319712c76add87
    forcestring: true
