helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-ui
    forcestring: true
  - name: image.tag
    value: latest@sha256:54000bcd12435e26e287596b6595f6500391d53540d9b946d5bf144d7f4187d5
    forcestring: true
