helm:
  parameters:
  - name: image.repository
    value: miguelsombrero/osaan-ui
    forcestring: true
  - name: image.tag
    value: latest@sha256:78646cdf8ad65a58033ab7093c0651e7dcbd0bf3c3afcb82452228a69142d554
    forcestring: true
