apiVersion: apps/v1
kind: Deployment
metadata:
  name: osaan-admin-ui-dep
  namespace: osaan-dev
  #annotations:
  #  prometheus.io/scrape: "true"
  #  prometheus.io/port: "4004"
  #  prometheus.io/scheme: http
  #  prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osaan-admin-ui
  template:
    metadata:
      labels:
        app: osaan-admin-ui
    spec:
      containers:
        - name: osaan-admin-ui
          image: miguelsombrero/osaan-admin-ui-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: osaan-admin-ui-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
