{
 "title": "Osaan Micrometer Overview",
 "tags": [
  "spring",
  "micrometer",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total[30s])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{state=\"closed\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "resilience4j_circuitbreaker_state{state=\"open\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Database Query Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "rate(jdbc_connections_seconds_sum[1m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, uri, method))",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 11 },
   "targets": [
    { "expr": "jdbc_connections_active", "legendFormat": "Active Connections" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
     "legendFormat": "Non-Heap"
    }
   ]
  },
  {
   "title": "JVM GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
     "legendFormat": "GC Pause"
    }
   ]
  }
 ]
}