apiVersion: testworkflows.testkube.io/v1
kind: WorkflowTrigger
metadata:
  name: smoke-trigger-osaan-dev
  namespace: testkube
spec:
  watch:
    resource:
      kind: Deployment
      namespace: osaan-dev
    selector:
      nameRegex: ".*"
  when:
    event: modified
  match:
    - path: ".status.availableReplicas"
      operator: changed
  run:
    workflow:
      name: cluster-smoke
    concurrencyPolicy: replace
    delay: 15s
---
apiVersion: testworkflows.testkube.io/v1
kind: WorkflowTrigger
metadata:
  name: smoke-trigger-istio-system
  namespace: testkube
spec:
  watch:
    resource:
      kind: Deployment
      namespace: istio-system
    selector:
      nameRegex: ".*"
  when:
    event: modified
  match:
    - path: ".status.availableReplicas"
      operator: changed
  run:
    workflow:
      name: cluster-smoke
    concurrencyPolicy: replace
    delay: 15s
---
apiVersion: testworkflows.testkube.io/v1
kind: WorkflowTrigger
metadata:
  name: smoke-trigger-keycloak
  namespace: testkube
spec:
  watch:
    resource:
      kind: Deployment
      namespace: keycloak
    selector:
      nameRegex: ".*"
  when:
    event: modified
  match:
    - path: ".status.availableReplicas"
      operator: changed
  run:
    workflow:
      name: cluster-smoke
    concurrencyPolicy: replace
    delay: 15s
