apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: smoke-trigger-osaan-dev
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    namespace: osaan-dev
    nameRegex: ".*"
  event: deployment-image-update
  action: run
  execution: testworkflow
  testSelector:
    name: cluster-smoke
    namespace: testkube
  concurrencyPolicy: replace
  delay: "15s"
---
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: smoke-trigger-istio-system
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    namespace: istio-system
    nameRegex: ".*"
  event: deployment-image-update
  action: run
  execution: testworkflow
  testSelector:
    name: cluster-smoke
    namespace: testkube
  concurrencyPolicy: replace
  delay: "15s"
---
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: smoke-trigger-keycloak
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    namespace: keycloak
    nameRegex: ".*"
  event: deployment-image-update
  action: run
  execution: testworkflow
  testSelector:
    name: cluster-smoke
    namespace: testkube
  concurrencyPolicy: replace
  delay: "15s"
