apiVersion: testworkflows.testkube.io/v1
kind: WorkflowTrigger
metadata:
  name: osaan-dev-deployment-trigger
  namespace: testkube
spec:
  watch:
    resource:
      kind: Deployment
      namespace: osaan-dev
    selector:
      nameRegex: ".*"
  when:
    event: modified
  match:
    - path: ".status.availableReplicas"
      operator: changed
  run:
    workflow:
      name: osaan-ui-e2e
    concurrencyPolicy: replace
    delay: 30s
