apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: osaan-ui-e2e
  namespace: testkube
  labels:
    app: osaan-ui
    type: e2e
spec:
  content:
    git:
      uri: https://github.com/MiguelSombrero/osaan
      revision: dev
      paths:
        - e2e

  container:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    workingDir: /data/repo/e2e
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "4"
        memory: 4Gi

  steps:
    - name: Install dependencies
      shell: |
        npm ci

    - name: Run Playwright tests
      env:
        NODE_ENV: development
      shell: |
        npx --yes playwright test
      artifacts:
        paths:
          - playwright-report/**/*
