apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: osaan-admin-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "osaan.admin.local"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: osaan-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: osaan-admin-vs
  namespace: istio-system
spec:
  gateways:
  - osaan-admin-gateway
  hosts:
  - "osaan.admin.local"
  http:
  - match:
    - uri:
        prefix: /api/
    - uri:
        prefix: /callback
    route:
    - destination:
        host: osaan-admin-backend-svc.osaan-dev.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: osaan-admin-ui-svc.osaan-dev.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: osaan-admin-backend-dr
  namespace: istio-system
spec:
  host: osaan-admin-backend-svc.osaan-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: osaan-admin-ui-dr
  namespace: istio-system
spec:
  host: osaan-admin-ui-svc.osaan-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: redis-master-dr
  namespace: osaan-dev
spec:
  host: redis-master.osaan-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE