apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-osaan
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: >-
      admin-backend=miguelsombrero/osaan-admin-ui-backend:latest,
      admin-frontend=miguelsombrero/osaan-admin-ui-frontend:latest,
      osaan-ui=miguelsombrero/osaan-ui:latest
    argocd-image-updater.argoproj.io/admin-backend.update-strategy: latest
    argocd-image-updater.argoproj.io/admin-frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/osaan-ui.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/git-branch: dev
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSombrero/osaan.git
    targetRevision: dev
    path: manifests
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: osaan-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true