apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-osaan
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSombrero/osaan.git
    targetRevision: dev
    path: .
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: osaan-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true