apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skill-catalog-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: skill-catalog=miguelsombrero/osaan-skill-catalog-service:latest
    argocd-image-updater.argoproj.io/skill-catalog.update-strategy: latest
    argocd-image-updater.argoproj.io/skill-catalog.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/skill-catalog.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/git-branch: dev
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSombrero/osaan.git
    targetRevision: dev
    path: charts/osaan-microservice
    helm:
      valueFiles:
        - values/skill-catalog-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: osaan-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
