apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skill-catalog-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSombrero/osaan.git
    targetRevision: dev
    path: charts/osaan-microservice
    helm:
      valueFiles:
        - values/skill-catalog-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: osaan-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
