name: osaan-admin-backend
svcName: osaan-admin-backend-svc
image:
  repository: miguelsombrero/osaan-admin-ui-backend
  tag: latest
port: 3001
probes:
  readiness:
    path: /health
    port: 3001
  liveness:
    path: /health
    port: 3001
prometheus:
  enabled: true
  port: "3001"
  scheme: http
  path: /metrics
appSecret:
  enabled: true
  secretName: osaan-admin-backend-secret
redis:
  enabled: true
istio:
  destinationRule:
    enabled: true
configMap:
  data:
    NODE_ENV: production
    PORT: "3001"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    TARGET_API: http://skill-catalog-svc:80
    SESSION_COOKIE_SECURE: "true"
    CORS_ENABLED: "true"
    CORS_ORIGIN: https://osaan.admin.local:9443
    REDIS_ENABLED: "true"
    REDIS_HOST: valkey-primary.osaan-dev.svc.cluster.local
    REDIS_PORT: "6379"
    BASE_URL: https://osaan.admin.local:9443
    LOGIN_REDIRECT_URL: https://osaan.admin.local:9443/skills
    LOGOUT_REDIRECT_URL: https://osaan.admin.local:9443
    KEYCLOAK_ENABLED: "true"
    KEYCLOAK_ISSUER_BASE_URL: https://keycloak.local/realms/osaan
    KEYCLOAK_CLIENT_ID: osaan-admin-ui
    TRACING_ENDPOINT: http://jaeger.istio-system:9411/api/v2/spans
