management:
  server.port: 4004
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
  endpoint.health.probes.enabled: true
  metrics.tags.application: ${spring.application.name}

spring:
  application:
    name: skill-catalog-service
  cloud:
    refresh:
      enabled: false # Compatibility issues with Spring Boot 4.0.0-SNAPSHOT
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always