logging:
  level:
    com.github.miguelsombrero.osaan: TRACE
    org.springframework.jdbc: DEBUG
    web: TRACE

management:
  server.port: 4003
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8094

spring:
  mail:
    host: localhost
    port: 1025
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest # Default RabbitMQ credentials for local development