management:
  server.port: 4004
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
  endpoint.health.probes.enabled: true
  metrics.tags.application: ${spring.application.name}
  health.rabbit.enabled: true

spring:
  application:
    name: competence-matching-service
  cloud:
    stream:
      bindings:
        skillCreated-in-0:
          destination: skill.created.queue
          group: competence-matching-service
      rabbit:
        bindings:
          skillCreated-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always