management:
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://osaan-db:5432/postgres
    username: postgres
    password: osaan_pass
  mail:
    host: mailhog
    port: 1025
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest # Default RabbitMQ credentials for local development