logging:
  level:
    com.github.miguelsombrero.osaan: DEBUG
    org.springframework.jdbc: DEBUG
    web: TRACE

management:
  zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans
  tracing.sampling.probability: 1.0

server:
  port: 8094

spring:
  mail:
    host: localhost
    port: 1025
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest # Default RabbitMQ credentials for local development