{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "osaan-ui.svcName" . }}-dr
  namespace: {{ .Values.namespace }}
spec:
  host: {{ include "osaan-ui.svcName" . }}.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}
