# This file contains encrypted SealedSecrets
# It is SAFE to commit this file to Git
# Generated on: Wed Dec 10 11:40:27 EET 2025
# 
# To update secrets:
#   1. Edit secrets-template.yaml (NOT committed to Git)
#   2. Run: ./seal-secrets.sh
#   3. Commit the updated sealed-secrets.yaml

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: osaan-ui-secret
  namespace: osaan-dev
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgCp8tqNwh7tOdmsvGQKlL6C8bx8P3LOfeRA+9aPgfm8sglloB7hLioG1R/q4mNXmx2CSjsueLrjfghTEnC9hUBgrfMQ0BWD1u8ya1faTEN1akCPn/2VXgHZdQnLQVG5QSMbfM7U+efdwY9+KMMP4yRLINKVtYzb9b141modaVTvr97ARmVHY4uzjHUW17IURCWMkB/LUg940+SH4kI84vCrHNjvytissQii1mUfjNBHSG9cTGRFcTzYcTcS6w9j0lwGkksIye3gIoV6JIJ7JoU1HAEkL4usKVg6MMgPN1lCcMTAXaTeuMt27gCQK67wK0N2+Z+ClWi3IZ0LUq/OImuPUr4BC8goX1lzM9ul9HEuHuEi546ksEvqoe/yFs7CCIbi5I4PJeYL/Dkz8tQdH9H2I+QqoGFyZXvvO48cvwe3TPY8SUVlceV+y8UoDznGZLCAJLBrdXOaDJ+CcmJp8in/SXyCS6s1rj6N2vESfdHcVLVAIi8o6HW9sFZq5X3L1jl/vti8oj83elmyRZsjbHegFvkmPVQv+q4mrE5qD88U/vRm4ZVIMC+XmCDGcKUINRc2Y4hKCTXtSktHlY/8eYkPcROJVPZ9I6cyLBHqCGZ52VllPueNQE8WMUxTDKn8xZipYyuUAT9lcZIFOkpzoofrFVpJ5Zd8pNh7bY6/JBWK5JydeETlV6j2IIs8ecHrCu2lRh1Dno+bX3S1UZg=
    NEXTAUTH_SECRET: AgC1fqxMMuGJmuZhf634k55XxZzOkN1Ku628Q03Xa6y+snqYyD8KVnctsWsiCh7sNs1IMqE20YqsVcUmWl4kj9Z5IhHPosMXDXhsOIxK9zgzThS9bGKvnEZPC4pCwE2/F0n9aGPqtKEjU9mIcHtmIKng8X7mlGoNxdWXdeA04m3t22TlMH5GEbrJz0pZcFyk3Lq7Y8T4tBls/BRFwxKksH+fu6JAAFhCeBveDgTCLdG9HX8HsDyMNc1mULpCAXTUZpViyuCEEgjGgF71L9NbtG0M7wXiPMlk7R92029+LcsUf3ZWnRLnRcyDAF+GZ3OEBmwo2oYQ7GLSuq4OgPriho4dJmfjOp1QDaT6xp1CvaFx/DFL36+AhUyTa96sqacxHFuamM+CsaQUx/VnDWa1l2FDEue8hgI7c6gsU6GQQfuLPrOvqp8EbuBxd1vALFlx0XBV8rOCR2pZwfu8j9bwWB5aCD+IsVBLFzdDf0G6zJcykO0cSKj4eGD2vziMZgnh7CvpJQ2CjIzQ+qg31609NyL3UTi/g7AP8E5RnyxFwHYHLK+sVK6PQro/5tLUU1BJFp4e89mSZxPs0Noc1lPVYLU1eolllnkbgUfUKrDkYpj2pZzYLL91/7BRlNFemGkR+hJBfthkqk9i2KAhrRKHX65uaqh8gAQSS0OOmnTkE8CLHm24nwOaZJWQpV08/amq+9ajdS72G7/YPZCInSnoY4KiY2x5ydxQTDvBi5tngsXjsy82V5ErWdso5A==
  template:
    metadata:
      creationTimestamp: null
      name: osaan-ui-secret
      namespace: osaan-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: osaan-admin-backend-secret
  namespace: osaan-dev
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgANwcvfGb/goFbhG9rKBTTGT51bId3T7lOTxcMFWWFqNcO8XzHL97KSBaL2R0y6yhcDs3+7DJTob+X4+0NBWnrwe/iDp2CAA9WGRPmMsmKAuiwVl51gHS8Q2Dxy7Mc6U+22oirpyvJo+Pw3/mq75PzGiKT5hCldjCccHMu4uFS2Lens2IVxRn9+gw0DiqMKzH8TMxO1C2I52fIF2wxy4EN5kpQLnG64Fh9CxFRbZt59eiO9sgkuldZYBefh11BBK512Uazr7d1au1yikKeswej7YCEov9rmRf+7OL+8PjDVizSwWxst6l+phJFJweUvX+pkgGQqIsDwo/RiU8wYgiKLHffOrBwqLEA9x4Hec9q4EDqCbEfwzHOZkPIun75HqrCObvimNp+ZdvWmh+jf3fJpD1YfX4WCjMLhu/YiH4q34ktKFShpF0WmuU6dj4XJx27m4YzEDlHvqVARAQzUWw2QDuTuK4WuEI03CVw95V08uzEJle7kxKU+coYijRTc9jvxbCzZCBM0n+AlMitX6QnVj3jtBlid4koB+Q4F83Gg/6uUBeIQqbhIgVi657n5cetTHhr2Jij2xBhET8Qnin8xrq699Bq/ohQHBi8dsu7j3goJxyS9y30JYtecfGjVQYJBLwOz9eb5sgwqIX8CJ+Jv+ne1GB0UKFUdn7RsxFlZQdlHs6Aux7zah9VIQz0RV1mtAG+2TPVHcRYYs7pDfv1ZkF8=
    SESSION_SECRET: AgB0eEalECX7DWQLTSCbVDQRUkmgek7uQZ/VjbhDrG6FVYlMXbDdPyAZPNzRe0Zl9o+YNzyDoYsR+JTHEv9iTBVXxkzu4XIlAj7DpV0uMK4b5pStQ2sJ65zp5bJZZ5oHq350PIF43xec1XgDHDf6+wSI3ZhJuWi7WBRlXLf2WmgzTVrI7+jzYcNMnKE6S3mdhpK8uTualejC/l3nr/qwaURUSprbOMKZik91P4H/CMdwtIlVNemsMGpfzqd18mdUyI0Kx2rxzGEHjWhYAL8UX7Tt0cM5Yx1vi0rgbemaHD4TkKpty4JAXK9BNHDQtGQQyBGwJykqQm6yfO12lGj+PROEPE3u13lZgWCSc/H+h8KSAs/Ykc9SKWdzln9MGCdKrQzJZD7Q4MrloCsFhtC7RFVfdVPavB5dvZQBHiGHbI5kR7o0PEmg6XcoknitRHPzR8zYXaQnLkU9/zCYKdc3Y/osLGboje0htIDp2eGx9ZTajIHxzvuDpWIeV4v65ySoBf6nL6XKuxvqEaEqBPCAexw6aTrPLWthbA22yM3g4mv6ZbHCPdzGns5w8wn3C+0DZ16rt34YX6PBNScIF8qZqvz+AtvJJTMv08odhGH28/GJAShJGfL0nBc+Q6hAxkUaT9uvUv6eU05hwJ6w218avSDzuOLAlpujBvcJ9Rl5qhI9DOuK4sUJmHMraWwLSbhqi7WPf7YIELjeog==
  template:
    metadata:
      creationTimestamp: null
      name: osaan-admin-backend-secret
      namespace: osaan-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: osaan-dev
spec:
  encryptedData:
    redis-password: AgB/bR24UaUO+e9zbxYNW8ZwP0paWJu7hEGH1M8MZlfA4G3y8cT3HIFdLXeKIc5B3YXiCY7inqJniUyY0LJn3mY5sgby1Mr9oU1zD313UFuGBRLmA5cUN2mnr3pcQ/Dlz9eAZzUa9qBneVoKTqxoVE6uBYuqikq6hQmoCKlhUDa7U4ouBvYdlOYB36jom25AtYsqczbagYjQrP/yptWncxRVL6P2TplP5Gl2Hh49/KMHuKm3GTucLvbQj+tPRsQj79wmZxQPAgpVvzgjtFh4LBIMSJvy3w5fCq/6AuAGHC8gIk6Bxf86Ligg841S+m2PFLSGheqJeZmox+pwRn8/nZiBBhYjDwiO06Xv3KU3eK143BHUialhoog0nRBmSHctTRkc/NRFTKlg2V5c5HEDWojbW6Gc10hNzOTWB0qUmLLmoWLvhyJnnuPk2xm1C7UXKjIxDaawNRvKfVufskDHkcDqcZyoeZork0HusxCmmRCMONqFKzLc3cdBFgp1utj/Li0iZGog6MG6UZBRUATbNrdymm8grcgY9eLs8QPZEL4qmm0uBZsuW3pVKAWGZ44eVCkAjsdkn93bX6RL/bKqMHKQC2g+jLY1WT38taXzeFiTU5rUdnKIp/SEfK+2nrITb7bTghmj4qviDy6NDNlG6tNO7rRNwHGx/kUwuTKfq7Of7vIAkNNtXzvjEvBHtXGM26yruMLezstYnw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: osaan-dev
    type: Opaque
