# This file contains encrypted SealedSecrets
# It is SAFE to commit this file to Git
# Generated on: Wed Dec 10 11:29:11 EET 2025
# 
# To update secrets:
#   1. Edit secrets-template.yaml (NOT committed to Git)
#   2. Run: ./seal-secrets.sh
#   3. Commit the updated sealed-secrets.yaml

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: osaan-ui-secret
  namespace: osaan-dev
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgBOmB0dDS4eRqfSGQMgZpWA/oOoEJBqJC6e9KwXzZgNAL3sO1xSn3o4UlF3g7e3Ssh66widqihNApdj97zAXKdk56TEp3YqxXYdSIr9GnU7OcY47qN3r1HB2H/gBGxbUh38wSgVbIMG5d6/6C4jHI0QwzZinSdiC8VRpL4LQAFV0/1NNW60ajhx2lzUSW/vf0tLhWGijfuHfSzByZML9XKh23H4lyDQ8Vjd86ptil1KgirDna4Y2DoVv1DpGISX9y7KkMNlye4jUjj0/ZAIDj890bc/Vq0wMcb/Wuy/Tha0hdGmYLVK3T9MFysGBFJ3ZfKK6aYg9Ab2dzPTw8ev/4qIDR5j4T2CSqW0QNdVmJNDrd2ExmESqfreUocDMkeEaeb8mEZ0U5ZuNa9Vp/FPTNvhzf5GrhT+wSY3VLHZxozZaBZ3uBsEsfOKm8fWDEu9CKl/gT/sZQh7omW+GTVD/mqJlEJsnl2Luf6SXUCOkjXYnJAyR1+q0FbYvkRRG1TRNNxlH5aTkPq9m+5QuGUdRfj2UQOr8ris529z13gIRoAPX4My8nqF1ggtaaPlBaNoCDy8WdDn1jv4ZZSeqH2WwL20XdagerVNfxDPdSrtJIkQthdaVGaUpElM5xHLScTliRl2t+I8+rEcGy7ZUWHgfrp0OHNJuyE5m1P6k0iJvcEGIg82iVhb8vohePeGhP/5IkE4WjPIhT2aWbNA0A8=
    NEXTAUTH_SECRET: AgBJ4lUveszhDbwIsxRvrLg8merNvS81SodNhdHsK+Z2qhNZD5bWZbhwoW+qP2wh2F6907c56cseQ631YvdzIFD1d3ucH9fY0VJnwRVV7shcWjgXjy67HufqRJ4vb5/iEoGEjUrVG+Wq6WxOMNtlfEWZ3F7ev4WWSPqHEiJ3V0ZxQIgwDOzfJPcWUn8Z1PSv1szoQw8m8i16g6TqIlEI57fPtBuEUAt/wMz6JUoLqgPVjZemGrme93BUI3//dXVE8hz2rPKZaGXT/CydmL7A2bvzqmuIOfOvRW/RbZwA1lGDa5WJaR5jiwyo9PK2SBs6mftronfdbcaiQx1ptyICuw9YfE9NauUUvXyvhqQtosXxYxtRY5kMtknilu9EjoRChcnxCazWqE5n/i1EmMcTvCK3v0B2EOuDW3uXWYSlApBDW6zLfoLkvosN3gku6Z1Xf1x3FBi6rAGcb7L1DFkfx4eFHfA7ll4SJX3U7actQEFL6MkJ7opN8NnsgGCng/9vEfcUiz3gcTG3UWkhauNh/xk3qbsZca69VphM1wQW0qu7mRpbqbXEHVDDDTDSIL9SU7HKgLQ2wPvqXBL3tsr9nJQRP32ZakxozMLCaKUd3WOw+TMuATU0wnzDK7o/hdvnurkw+qRt08UHbAzs3cu3xu3VN1IkBuJ3c2+AI4LdHfNOwFd4a6nxFv4abZmDMyqjRjAp++WGTt2kZZVoYmOBhizMNwMmTeXqEKarbyLQIrU+rmUGgSpH6pQ1Rg==
  template:
    metadata:
      creationTimestamp: null
      name: osaan-ui-secret
      namespace: osaan-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: osaan-admin-backend-secret
  namespace: osaan-dev
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgAlN1e4F9yQlYlV9BD0dG48Il6dZtxXWGL0BY08+pU5A5wY3xLXbBgvAmdSlhuuS7MtsAHUPLOl3zZYHO3C1hzrCxLfbqvjcLgamIg4eHbzACt+MMpmlfDgxAFTz7pQruDwIU5Pi+38wXzdXnpFIU8NKyGvgYEfsHsoL6oBlszMUzuN0k00AgqJg5ZAkHLJd1wJKCzcEHKQOl8R2e9LmztyYNFaLcaun4Pq80jmjiSeNa+G3LoIziu3ABiC/ZJ6SjzvQISE59gK4iYdk+GDyIhSmxhP2uBHLfzSodJUWdjmXbr2LDJsgh0WGACiNlatsfSOVwWffkNH9Dm3JYxrV31R+SH8HB5pg1c7F1kvvKuoKU6UiMGNQKksKNPiL/I4sDgw9DnqbFmrczLYFZxPBC9/JzmBwiaT2rNGAMO1zHIpkj6g7IZ8VvZkxS9oJhroQ+Oh6y7duuRm13aR6Icn+qAtpUl0nkwbg3nISk1le3K/zZKnGCN4VwHUnVNLlzdTne3EnmEW7GgWA9rT8bYzKSJC1G1NLTKwGkelbJL7vgIw/06MsMYJvj8CXQ+0BDEp2j239bGEXGpspDOSU77NPsfl7MIMu4VPvTpCadz35MOVFJ3l0H7ca/1qj4UeWp81IzdigHTLIUYx66tnKGVyq+OH2PaQynOwhBbQdYxKIt7+Ar09mBkK4Nm4RjcdUICA3xPZpJl72HZoRrIoRiQ7+5FeKwY=
    SESSION_SECRET: AgCKRb0GMXpKeCbeM0pXt0HpfoQfhJgVHGcMKaF76psC3kItOCIRH8zpcJ3LhI+zrEd3rPQHgx29ONESCpnk/un8DZ10uaPWJhZ4pzkW6NgaPCgY3p3JThyJ/bvVhkWs4v5l3N8Ph81eezHR9gLNSDhpA5Z9Xc6e6iyMzenLWXFbSEtrDe+REmZQnXHrEOCIvtsv3AsZtoEXw8XonerBgmuxt1eGA5VuY/R//hhUxnkqZjz+cSEoMQlp+Q6VTj0GGimr6ofNZlolf3E4q1ebNioWVzUa8t/chkM9v9fbcKpIvlWn6RhSvXLPubhmr5gaK8DSligESeXZAOKDJzaqU+REoLBp1HyeExeL+HB32bc+uposnXk5Alv2KftaK86ZLSAnL9y3aCfcNEwLrCXa6p2+vXbjNw8vw6bVeCR6K5Pg8KkV/8U6j2/nT4YcdxOoTLoskmqtoKon4s3EN9r+narhpI3D8Q/9c90u8W/M1jrf6dFw8v8XAc7fGaA5NCe6LwwYAKd2o9My9RQN/yFkGwH3YNmABUcQqkmfmu/brLgtsi+S2qikXM3R2Aj5g1d+UoOHw6P9R0S1Q7xUueb+adDHelncvNc+cxDrYGR7bAfbfFTGfKGVJ/NGLouv2lPDIknzE2riRA1ndwN3EiOg0InoJIRL285R2h/OnG6Js+KhR15WxRDRIWwF92/M1w4A14D4GdZdi9m/7A==
  template:
    metadata:
      creationTimestamp: null
      name: osaan-admin-backend-secret
      namespace: osaan-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: osaan-dev
spec:
  encryptedData:
    redis-password: AgBtWfSezxll9wRVjTyIlMuiJUqduU6y5V7sKPN96hqQ8CKCUvT+Z0rCdSwtVu5QzF9EYxEyBo086BsRpZj3gfQQcvdaClg99SP9COmoFgz+JCKMdeTaVbps396ytTyKKyy8jB6NtNwd+xPtd9ciSPOtMnJPFkuD7k5AAY+FeTOwLm/i4EBSVW6GJHnmHAdj4nCTQ42BjWYOuEz/fokICfPLvF6t+Zny7zEXYlB+aOTn5+YlL7Hl7265t0+MeqDNx/jLt+JZhkKgXIp97Rub1Jg122FZb0x9LSPg7xwuyFSOgY9CQ8ck/3Dw6qVbPIY6HnkeOBK+DW+PXvJDe5jZ1vfKp1RPDBS2P/F+uqqn7Cvvo/vm8ismwJouyj1kM8qEND0IdyC0SaDGaFAmyiZQjgGT6dDxkDw+z2gyqTcvcRULcLYpIxuajoWbOSQ3bm7URwcAfcJR84TrX+jQOlhvbPYYX4h/MiVrlMGvZHY2WPyUp+HDGKirB/sK7vrdQu55KbbveH5XWoR2M+YlEo5YvoVHwoPYj+UrI2Ys4QIgXjONZpo5NaLpJ8Hed1b9gxDdfNhCtPoi9m8faqxT/BGwoNaK3zHFe7GEu/0NKs4AEpJ0s3nXciMdeArlP+XwFJrJUZBCQ6HQBAQEp4eo3GyKty19iXaecBjUAx2dpBu31wdhmI2WwcQeRt6Zx/89Nig02Dr1Y7cU9veQGw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: osaan-dev
    type: Opaque
