apiVersion: v1
kind: Secret
metadata:
    name: osaan-ui-secret
    namespace: osaan-dev
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:4bkJoFNAALoDmIm2cLisLmvNAwxzOjIIo2IoUB+lXy859tYV6nMLYcE=,iv:9TXgNqlyoH33g5hh8GFJNwTsrpK3/4SUdkGiU40qcOM=,tag:dKyrjo3VMrCNmBOulQlvyA==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:V3VQg6mAwBHm8A9R,iv:Pgln2G6XXOQ80Mo9QfY4pRWrmxBeOVsmo/oyD0pglQE=,tag:aHgHM/3C6ONUyuGVYUSWRA==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNE5aL05RalE3cGxzUWwv
            Yy9FVzhKdUZMU0VsUkwzZnltbVlzNXVFclNjCmVYdUxLeHBZcW9mNmEyNE04SHZI
            b3RDTkpCN3lBUitNZWVQbDh5U1RaWXcKLS0tIG9KUmR3VWNRK2haL2ptQWd6azNU
            MFZCZk02YWNlcmlnWXRVYWpOUXczaDAKaK0ybt6JW693w9Kqj3j9RfphwGLVm/zC
            W/lFi7EWUCEwxBRcdZxWBuOU4H2eI5I+vbAx4/OjtgSY9KK0DPmrLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T10:01:42Z"
    mac: ENC[AES256_GCM,data:sbc7mCcW5iYBQMlqVrO3lru0PcH1p110burhuNP5CILC5FGjm6omRpE+ZIW0lVIP8yN69mH/lhqYeSXm5k6JuHNpTwtIh8zRwLqxkFJpNr2fzIwOCbP/W3u5VqkwA12JxMpUgOL6RW4w6PsrNU6MX7V/WQqADkZ0Q9qShiMmkYk=,iv:kO4v32MjcU2mkwiO4UEiE4rQdbO5+wBV2+kR7Y2Gwnc=,tag:54ZUWw7i9hqTmexCSDunbQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: osaan-admin-backend-secret
    namespace: osaan-dev
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:hTAMgX/svwc=,iv:6r5vuukTwV7BvlSA+t7y53ME+7IAN6ZD4sKvF6cqsXQ=,tag:VQC/3VUldFSnxvlXFg0NEw==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:rNwhfxmLn3A2HtblAV1hc2ln,iv:bhnceW4XjUwrCPW549muP+QoyZtGRa19YR8SvWMpGaU=,tag:GVF5KOCBaTPBwYasOd6a4Q==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNE5aL05RalE3cGxzUWwv
            Yy9FVzhKdUZMU0VsUkwzZnltbVlzNXVFclNjCmVYdUxLeHBZcW9mNmEyNE04SHZI
            b3RDTkpCN3lBUitNZWVQbDh5U1RaWXcKLS0tIG9KUmR3VWNRK2haL2ptQWd6azNU
            MFZCZk02YWNlcmlnWXRVYWpOUXczaDAKaK0ybt6JW693w9Kqj3j9RfphwGLVm/zC
            W/lFi7EWUCEwxBRcdZxWBuOU4H2eI5I+vbAx4/OjtgSY9KK0DPmrLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T10:01:42Z"
    mac: ENC[AES256_GCM,data:sbc7mCcW5iYBQMlqVrO3lru0PcH1p110burhuNP5CILC5FGjm6omRpE+ZIW0lVIP8yN69mH/lhqYeSXm5k6JuHNpTwtIh8zRwLqxkFJpNr2fzIwOCbP/W3u5VqkwA12JxMpUgOL6RW4w6PsrNU6MX7V/WQqADkZ0Q9qShiMmkYk=,iv:kO4v32MjcU2mkwiO4UEiE4rQdbO5+wBV2+kR7Y2Gwnc=,tag:54ZUWw7i9hqTmexCSDunbQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: osaan-dev
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:K3LD2oEU4/A=,iv:uti9UP2ABiXkNe3L8Z/v1poxYL6ELF5vwdWbDG3EMlU=,tag:S35Te0gQROBWMS/rIKyWjg==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNE5aL05RalE3cGxzUWwv
            Yy9FVzhKdUZMU0VsUkwzZnltbVlzNXVFclNjCmVYdUxLeHBZcW9mNmEyNE04SHZI
            b3RDTkpCN3lBUitNZWVQbDh5U1RaWXcKLS0tIG9KUmR3VWNRK2haL2ptQWd6azNU
            MFZCZk02YWNlcmlnWXRVYWpOUXczaDAKaK0ybt6JW693w9Kqj3j9RfphwGLVm/zC
            W/lFi7EWUCEwxBRcdZxWBuOU4H2eI5I+vbAx4/OjtgSY9KK0DPmrLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T10:01:42Z"
    mac: ENC[AES256_GCM,data:sbc7mCcW5iYBQMlqVrO3lru0PcH1p110burhuNP5CILC5FGjm6omRpE+ZIW0lVIP8yN69mH/lhqYeSXm5k6JuHNpTwtIh8zRwLqxkFJpNr2fzIwOCbP/W3u5VqkwA12JxMpUgOL6RW4w6PsrNU6MX7V/WQqADkZ0Q9qShiMmkYk=,iv:kO4v32MjcU2mkwiO4UEiE4rQdbO5+wBV2+kR7Y2Gwnc=,tag:54ZUWw7i9hqTmexCSDunbQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-initial-admin-secret
    namespace: argocd
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:CoA3jHA=,iv:29ge5gC8OvmtqTf2Em5PHJwc5JhrO9gnXQ23icMXMug=,tag:xdaeCNIehfdA5B2zy8wfaQ==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNE5aL05RalE3cGxzUWwv
            Yy9FVzhKdUZMU0VsUkwzZnltbVlzNXVFclNjCmVYdUxLeHBZcW9mNmEyNE04SHZI
            b3RDTkpCN3lBUitNZWVQbDh5U1RaWXcKLS0tIG9KUmR3VWNRK2haL2ptQWd6azNU
            MFZCZk02YWNlcmlnWXRVYWpOUXczaDAKaK0ybt6JW693w9Kqj3j9RfphwGLVm/zC
            W/lFi7EWUCEwxBRcdZxWBuOU4H2eI5I+vbAx4/OjtgSY9KK0DPmrLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T10:01:42Z"
    mac: ENC[AES256_GCM,data:sbc7mCcW5iYBQMlqVrO3lru0PcH1p110burhuNP5CILC5FGjm6omRpE+ZIW0lVIP8yN69mH/lhqYeSXm5k6JuHNpTwtIh8zRwLqxkFJpNr2fzIwOCbP/W3u5VqkwA12JxMpUgOL6RW4w6PsrNU6MX7V/WQqADkZ0Q9qShiMmkYk=,iv:kO4v32MjcU2mkwiO4UEiE4rQdbO5+wBV2+kR7Y2Gwnc=,tag:54ZUWw7i9hqTmexCSDunbQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
