apiVersion: v1
kind: Secret
metadata:
    name: osaan-ui-secret
    namespace: osaan-dev
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:FdM2VhqFhJ7PqattfAaszIDhyofhcXowWajwg0495TgAqM47DgitRB4=,iv:9Hwdg6ZsFsWkziL+AoDbeWoDnYp7ALfKcYsIfE5p7Lw=,tag:ieHHL84TYBObz0gS+BG3aQ==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:5tpotyj102+4L5dL,iv:ZaGXPb2AK/XGZw4ajUmjhZcy7vkm1sDu9eLRLdt65pY=,tag:7DsNSywhjKU8AoB+u6XNXA==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUFI0Qk4xUEpGcWdKSFlo
            RDM5azdIQWJlcmtWV1Jhc0RMUkhEMWZXL0N3Cm54TjNJa0hGSzRlNnBTQ3dRZnc3
            ZUMvNVNud1NFb1ovWnI5VUQxd1hVckUKLS0tIFg4M1BqL1drVW90V2MyblM0eSsz
            cThRdmZXaWYzbEg1Y0MrSHkyUGw1M0kKi+omS99UIgdM5RCt+sYik7YJUTNhSklI
            t5nwyNmy9QiWMg2yaDsBD9/+hXQY/BPd43iVf+w/ZVlcnFLQ4u3rDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T05:27:44Z"
    mac: ENC[AES256_GCM,data:uaxuJOKN1fbnSUSHMKw4sAKH5kfbuJmtpF8GnvA3hdmMi+Dtf0hLqt99F6z/J5FyuQBJG9V2FsR877LYYizbwO7R3ACpldxMClvDMBkul39sS/LDn2qqgVTl/1QKXLFQex0GWuk1mkD2yMqDOQpyPHPsrPOQy5ldBm8/ez62/hg=,iv:tKP0HtLoysA1TbNMVSfPgRzgPcSOTtokRh8eOWdrwSU=,tag:bB6xBTuk7/U5klCg4XTNIQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: osaan-admin-backend-secret
    namespace: osaan-dev
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:NNT5keIBbvA=,iv:9WezTC2IMBLh7oFkJTzO7t4joV5+w8cqpX1lnPEAK9k=,tag:6/+rypbCfmn5TqTu4wLtdw==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:Z51bhPUtYYFaoQCL7IQwMZQq,iv:jMyBtDGE79DFEFumD3mhbs0grGdM/q+byq/uaLyXGzA=,tag:jnbhtZAbcvpwP5Ls9yxnhQ==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUFI0Qk4xUEpGcWdKSFlo
            RDM5azdIQWJlcmtWV1Jhc0RMUkhEMWZXL0N3Cm54TjNJa0hGSzRlNnBTQ3dRZnc3
            ZUMvNVNud1NFb1ovWnI5VUQxd1hVckUKLS0tIFg4M1BqL1drVW90V2MyblM0eSsz
            cThRdmZXaWYzbEg1Y0MrSHkyUGw1M0kKi+omS99UIgdM5RCt+sYik7YJUTNhSklI
            t5nwyNmy9QiWMg2yaDsBD9/+hXQY/BPd43iVf+w/ZVlcnFLQ4u3rDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T05:27:44Z"
    mac: ENC[AES256_GCM,data:uaxuJOKN1fbnSUSHMKw4sAKH5kfbuJmtpF8GnvA3hdmMi+Dtf0hLqt99F6z/J5FyuQBJG9V2FsR877LYYizbwO7R3ACpldxMClvDMBkul39sS/LDn2qqgVTl/1QKXLFQex0GWuk1mkD2yMqDOQpyPHPsrPOQy5ldBm8/ez62/hg=,iv:tKP0HtLoysA1TbNMVSfPgRzgPcSOTtokRh8eOWdrwSU=,tag:bB6xBTuk7/U5klCg4XTNIQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: osaan-dev
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:+K7QvTcMy1s=,iv:etdipCsGS1MR/q70ytrXfcBoui/BxynszxHyG7Rxgrc=,tag:I9O942eOuU1a5Q/wJferOQ==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUFI0Qk4xUEpGcWdKSFlo
            RDM5azdIQWJlcmtWV1Jhc0RMUkhEMWZXL0N3Cm54TjNJa0hGSzRlNnBTQ3dRZnc3
            ZUMvNVNud1NFb1ovWnI5VUQxd1hVckUKLS0tIFg4M1BqL1drVW90V2MyblM0eSsz
            cThRdmZXaWYzbEg1Y0MrSHkyUGw1M0kKi+omS99UIgdM5RCt+sYik7YJUTNhSklI
            t5nwyNmy9QiWMg2yaDsBD9/+hXQY/BPd43iVf+w/ZVlcnFLQ4u3rDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T05:27:44Z"
    mac: ENC[AES256_GCM,data:uaxuJOKN1fbnSUSHMKw4sAKH5kfbuJmtpF8GnvA3hdmMi+Dtf0hLqt99F6z/J5FyuQBJG9V2FsR877LYYizbwO7R3ACpldxMClvDMBkul39sS/LDn2qqgVTl/1QKXLFQex0GWuk1mkD2yMqDOQpyPHPsrPOQy5ldBm8/ez62/hg=,iv:tKP0HtLoysA1TbNMVSfPgRzgPcSOTtokRh8eOWdrwSU=,tag:bB6xBTuk7/U5klCg4XTNIQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
