apiVersion: v1
kind: Secret
metadata:
    name: osaan-ui-secret
    namespace: osaan-dev
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:0aQq00sLjHrOGiuKkG6ivmK6kUukH+gyP8x3iboEXP5UBT78AbIXupc=,iv:prknpSwj4Nts+sxfAAsV4AqOBZkTrdQWIUTQufoV3+4=,tag:Dxlk09Tzm4MfWb7eeWPkTQ==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:qT5zUOwHfbXbtgfN,iv:HcrzkFbdHbBk/zQg6VbgoxlKs69fUqG348MYWtYXZpE=,tag:iga7jRELNWHtOJdZ6jq6uw==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFBCMUJTUG9jVEVpY0J5
            dXZ6eDRnd3k4dFdHSi9tSGFWdyt1elFXaEFjCmJyclBEdVZaV0NaUVROMjZ0YTFO
            WnlTbjJYQXRFeWpyVkJiMjFzM1F1SFkKLS0tIC8rUEZ3VHJhRElMTUhSQmJmei9l
            WWQ5UmdSWmpJM3pPSkIvV2lCWXJzM0UKGTTQZruEJIR5yIgLfLDHFjq8ZdXg8mvh
            iq4/DHnZG8Ln+rn25N1J05k2rrs/bFfizO6jbypibThYhJF5fJwQZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T05:18:06Z"
    mac: ENC[AES256_GCM,data:u3gK2rAeMT/ITmtEWEX+USk0BGWvcLnnE7iMcXH7+lLF/aQoNvA4J4RnWx7JHgiQVaNnxZp7PZgQ3kevmsEDTDkeY4NF4pZcEQaLmgYsmV+/WaLpQUWs0QGwrD3lHjytLBvoBC2DyzzDXFARPjjzFibvy7/cBIE2ZqO2zVTU0wM=,iv:3vNxNBOky0XvOfuvFAGqE6nVUc+9J8X9AbNtktkSfR8=,tag:5JNSXAA0gw4RKEz0onH6bA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: osaan-admin-backend-secret
    namespace: osaan-dev
type: Opaque
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:MuS4waM+2kc=,iv:2KL3XMfhcyQ/Y/5Sw2l3oGfG91GujDZx6jqZPUSoZss=,tag:3fUvUlX+VsvYLbPOiRlAQg==,type:str]
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:86BMjZjWaKo+Y1z3hGKpGFxh,iv:fuC40o0gwxQSL7KNfxJqokVyPLymimesyVkq0suFZsA=,tag:/Mm3g3ku2BkOOvqpGrHaeA==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFBCMUJTUG9jVEVpY0J5
            dXZ6eDRnd3k4dFdHSi9tSGFWdyt1elFXaEFjCmJyclBEdVZaV0NaUVROMjZ0YTFO
            WnlTbjJYQXRFeWpyVkJiMjFzM1F1SFkKLS0tIC8rUEZ3VHJhRElMTUhSQmJmei9l
            WWQ5UmdSWmpJM3pPSkIvV2lCWXJzM0UKGTTQZruEJIR5yIgLfLDHFjq8ZdXg8mvh
            iq4/DHnZG8Ln+rn25N1J05k2rrs/bFfizO6jbypibThYhJF5fJwQZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T05:18:06Z"
    mac: ENC[AES256_GCM,data:u3gK2rAeMT/ITmtEWEX+USk0BGWvcLnnE7iMcXH7+lLF/aQoNvA4J4RnWx7JHgiQVaNnxZp7PZgQ3kevmsEDTDkeY4NF4pZcEQaLmgYsmV+/WaLpQUWs0QGwrD3lHjytLBvoBC2DyzzDXFARPjjzFibvy7/cBIE2ZqO2zVTU0wM=,iv:3vNxNBOky0XvOfuvFAGqE6nVUc+9J8X9AbNtktkSfR8=,tag:5JNSXAA0gw4RKEz0onH6bA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: osaan-dev
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:jU18sUAcec4=,iv:PnX3WUCCKiowKgFIwPTgu6c2G/tL0gVxYxXwNRNoFvY=,tag:SYKtR+iCMAbRyuHu0ay8qA==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFBCMUJTUG9jVEVpY0J5
            dXZ6eDRnd3k4dFdHSi9tSGFWdyt1elFXaEFjCmJyclBEdVZaV0NaUVROMjZ0YTFO
            WnlTbjJYQXRFeWpyVkJiMjFzM1F1SFkKLS0tIC8rUEZ3VHJhRElMTUhSQmJmei9l
            WWQ5UmdSWmpJM3pPSkIvV2lCWXJzM0UKGTTQZruEJIR5yIgLfLDHFjq8ZdXg8mvh
            iq4/DHnZG8Ln+rn25N1J05k2rrs/bFfizO6jbypibThYhJF5fJwQZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T05:18:06Z"
    mac: ENC[AES256_GCM,data:u3gK2rAeMT/ITmtEWEX+USk0BGWvcLnnE7iMcXH7+lLF/aQoNvA4J4RnWx7JHgiQVaNnxZp7PZgQ3kevmsEDTDkeY4NF4pZcEQaLmgYsmV+/WaLpQUWs0QGwrD3lHjytLBvoBC2DyzzDXFARPjjzFibvy7/cBIE2ZqO2zVTU0wM=,iv:3vNxNBOky0XvOfuvFAGqE6nVUc+9J8X9AbNtktkSfR8=,tag:5JNSXAA0gw4RKEz0onH6bA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: operators
type: Opaque
stringData:
    argocd-admin-password: ENC[AES256_GCM,data:eDyv2dW9Xbp/aTlp3/ySbzu7BH0xxWr18g==,iv:LhRBVoKG5cBUwk4F21KFdGROpAtOVpFsLSUprzYQTn8=,tag:hk6x2Q4qxeCUOSBjUaxlPg==,type:str]
sops:
    age:
        - recipient: age1wfrlkmzsms3qf29fx266mv2pm030405e3chgtatpssj594kkt3jsaa2j0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFBCMUJTUG9jVEVpY0J5
            dXZ6eDRnd3k4dFdHSi9tSGFWdyt1elFXaEFjCmJyclBEdVZaV0NaUVROMjZ0YTFO
            WnlTbjJYQXRFeWpyVkJiMjFzM1F1SFkKLS0tIC8rUEZ3VHJhRElMTUhSQmJmei9l
            WWQ5UmdSWmpJM3pPSkIvV2lCWXJzM0UKGTTQZruEJIR5yIgLfLDHFjq8ZdXg8mvh
            iq4/DHnZG8Ln+rn25N1J05k2rrs/bFfizO6jbypibThYhJF5fJwQZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T05:18:06Z"
    mac: ENC[AES256_GCM,data:u3gK2rAeMT/ITmtEWEX+USk0BGWvcLnnE7iMcXH7+lLF/aQoNvA4J4RnWx7JHgiQVaNnxZp7PZgQ3kevmsEDTDkeY4NF4pZcEQaLmgYsmV+/WaLpQUWs0QGwrD3lHjytLBvoBC2DyzzDXFARPjjzFibvy7/cBIE2ZqO2zVTU0wM=,iv:3vNxNBOky0XvOfuvFAGqE6nVUc+9J8X9AbNtktkSfR8=,tag:5JNSXAA0gw4RKEz0onH6bA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
