package com.github.miguelsombrero.osaan.employee_service.employee;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Employee {
    @Schema(description = "Unique identifier of the employee. Generated by the database", example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    private UUID id;
    @Schema(description = "First name of the employee", requiredMode = Schema.RequiredMode.REQUIRED)
    private String firstName;
    @Schema(description = "Last name of the employee", requiredMode = Schema.RequiredMode.REQUIRED)
    private String lastName;
    @Schema(description = "Email address of the employee", requiredMode = Schema.RequiredMode.REQUIRED)
    private String email;
}
